---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"    


  - name: download tomcat
    get_url: 
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz
      dest: /opt


  - name: extraxt tomcat
    unarchive: 
      src: /opt/apache-tomcat-8.5.87.tar.gz
      dest: /opt
      remote_src: yes
         
  - name: change permissions
    file:
      path: /opt/apache-tomcat-8.5.87/bin/startup.sh
      mode: '0777'

  - name: start tomcat service
    shell: nohup ./startup.sh
    args: 
      chdir: /opt/apache-tomcat-8.5.87/bin


